{{- if .Values.storage.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.type }}-sc-scribe
{{- if eq .Values.storage.type "efs" }}
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.global.fsId }}
  directoryPerms: "700"
{{- end }}
{{- end }}