apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kerno:kerno-ns-admin
  namespace: {{ .Values.global.namespace }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kerno:gaia-kerno-admin-binding
  namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kerno:kerno-ns-admin
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.serviceAccountName }}
    namespace: {{ .Values.global.namespace }}