{{ include "gen-tls-certs" . -}}
apiVersion: v1
data:
  INSTALLATION_KEY: {{ .Values.apiKey | b64enc }}
  CLUSTER_ID: {{ .Values.clusterId | b64enc }}
kind: Secret
metadata:
  name: installation-config
  namespace: {{ .Values.global.namespace }}
type: Opaque
---
apiVersion: v1
data:
  tls.crt: {{ .Values.global.tlsCert }}
  tls.key: {{ .Values.global.tlsKey }}
kind: Secret
metadata:
  name: kerno-tls-certs
  namespace: {{ .Values.global.namespace }}
type: Opaque
