apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/app: nanobe
    app.kubernetes.io/component: preon
    app.kubernetes.io/part-of: nanobe
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: nanobe
      app.kubernetes.io/component: preon
      app.kubernetes.io/part-of: nanobe
  template:
    metadata:
      labels:
        app.kubernetes.io/app: nanobe
        app.kubernetes.io/component: preon
        app.kubernetes.io/part-of: nanobe
    spec:
      hostPID: true
      containers:
        - name: main
          image: {{ .Values.global.imageRepository }}/{{ .Chart.Name }}:{{ .Values.global.preon.image.tag | default .Values.global.environment }}
          imagePullPolicy: Always
          env:
            - name: HOST_FS_PATH
              value: /host
            - name: ENVIRONMENT
              value: {{ .Values.global.environment }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | default .Values.global.logLevel }}
            - name: QUARK_WS
              value: ws://quark-service/ingestor
            - name: QUARK__ENDPOINT_URL
              value: ws://quark-service/ingestor
            - name: SCRIBE__ENDPOINT_URL
              value: http://scribe/errors
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}