apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "app-chart.selectorLabels" . | nindent 6 }}